[package]
name = "scene-node"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "scene-node"
path = "src/main.rs"

[dependencies]
base64.workspace = true
dora-node-api.workspace = true
eyre.workspace = true
image.workspace = true
json-config-store.workspace = true
nalgebra.workspace = true
scene-core.workspace = true
reqwest.workspace = true
robot-arm-messages.workspace = true
serde.workspace = true
tokio.workspace = true
