FROM moveit/moveit2:jazzy-release

RUN apt-get update \
    && apt-get install --yes --no-install-recommends \
        python3-pip python3-serial \
        ros-jazzy-joint-state-topic-hardware-interface \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY requirements-hardware.txt /tmp/requirements-hardware.txt
RUN python3 -m pip install --no-cache-dir --no-deps --break-system-packages \
    -r /tmp/requirements-hardware.txt
