sensors:
  - depth_point_cloud
depth_point_cloud:
  sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
  point_cloud_topic: /perception/depth/points
  max_range: .inf
  point_subsample: 1
  padding_offset: 0.0
  padding_scale: 1.0
  max_update_rate: 0.0
  filtered_cloud_topic: /perception/depth/points_filtered
